# Minimal configuration for running on GPUs with very limited VRAM (4GB or less)

# Data configuration
data:
  root:  "/Users/bharadwajmadiraju/Downloads/flickr8k_audio" # "../../clotho_audio_evaluation"
  batch_size: 2                # Very small batch size
  num_workers: 1               # Minimal worker count
  max_text_length: 32          # Reduced text length
  audio_length: 3              # Reduced audio length
  audio_sample_rate: 16000
  image_size: 224              # Smaller images
  subset_size: 40             # Tiny subset for testing

# Model configuration
model:
  embedding_dim: 512            # Minimal embedding dim
  dropout: 0.3

  # Text encoder configuration - using tiny model
  text:
    model_name: "distilroberta-base"
    freeze_base: true
    output_dim: 768

  # Audio encoder configuration
  audio:
    model_name: "MIT/ast-finetuned-audioset-10-10-0.4593"
    freeze_base: true
    output_dim: 768

  # Image encoder configuration
  image:
    model_name: "google/vit-base-patch32-224-in21k"
    freeze_base: true
    output_dim: 768

# PEFT configuration - using minimal LoRA
peft:
  enabled: true
  method: "lora"

  # Text LoRA configuration
  text:
    rank: 2                    # Minimal rank
    alpha: 4                   # Reduced alpha
    dropout: 0.1
    target_modules: ["query", "key", "value", "dense"]

  # Audio LoRA configuration
  audio:
    rank: 2
    alpha: 4
    dropout: 0.1
    target_modules: ["query", "key", "value", "dense"]

  # Image LoRA configuration
  image:
    rank: 2
    alpha: 4
    dropout: 0.1
    target_modules: ["query", "key", "value", "dense"]

# Training configuration
training:
  num_epochs: 5            # Just one epoch for testing
  learning_rate: 5e-5
  weight_decay: 0.01
  device: "cuda"
  output_dir: "./outputs/minimal"
  log_interval: 2
  save_interval: 1
  eval_interval: 1
  mixed_precision: true        # Enable mixed precision
  gradient_checkpointing: true # Enable gradient checkpointing
  text_only: false             # Set to true to use only text encoder
  audio_only: false            # Set to true to use only audio encoder
  image_only: false            # Set to true to use only image encoder